Rename calendar-day variable names
primer/primitives pull request #111
Opened 2021-05-27 02:08 UTC by jonrohan

This renames the calendarGraph names from `calendar-graph-day-L1-bg` to `calendar-graph-day-1-bg`

2021-05-27 02:16 UTC, simurai approved these changes
Is the `L` meant for "level"? Yeah, should be simpler without.

And we might can get away with just a `patch` since this seems VERY specific and hopefully not really used outside of dotcom.

2021-05-27 02:17 UTC, jonrohan commented
How about actually we remove them

2021-05-27 05:17 UTC, simurai requested changes
The `calendarGraph` colors are [now available on dotcom](https://github.com/github/github/pull/181475/commits/77db4b41346300b28a46258a0caa38caa030fd2c). So I guess we could move them to `deprecated.ts`.

2021-05-27 14:26 UTC, colebemis approved these changes

2021-05-28 01:52 UTC, simurai commented
> If they are already on dotcom, can we just remove them from Primitives now?

Yeah, we could, but if we wanna follow semver somewhat strictly, it would need to be a major version. Is that ok? I think there are a few other variables that should be un-used.. like #82 or #81. But I closed those PRs again so that we can release them all in a bigger major version once v2 is done instead of making multiple smaller major versions that might be harder to keep track of? 🤔 

For Primer CSS @jonrohan started to test a `next_major` setup https://github.com/primer/css/pull/1402. So that it's possible to merge major changes without triggering a major release. In case we wanna consider that for Primitives too.

2021-06-08 08:09 UTC, simurai commented
> If they are already on dotcom, can we just remove them from Primitives now?

Ok, I think you're right. The "old" variable names like `calendar-graph-day-L1-bg` got already removed in one of the past few patch releases without anyone reporting it. So no need to wait for the next major release to remove the "new" variables like `calendar-graph-day-l-1-bg`. I made an alternative PR here: https://github.com/primer/primitives/pull/130

2021-06-09 00:36 UTC, closed without merging