Add overlay-shadow
primer/primitives pull request #135
Opened 2021-06-11 12:08 UTC by simurai

This add `overlay-shadow` variable. Meant to be used for the new [`Overlay`](https://primer.style/components/Overlay) component. Output:

```scss
--color-overlay-shadow: 0 1px 3px rgba(27,31,36,0.12), 0 8px 24px rgba(140,149,159,0.2); // light
--color-overlay-shadow: 0 1px 3px rgba(1,4,9,0.12), 0 16px 32px rgba(1,4,9,0.85); // dark
```

2021-06-11 18:13 UTC, vdepizzol commented
@simurai @auareyou can you confirm this is how your proposal would look on these different canvases?

![Preview of shadows in under different themes and canvases](https://user-images.githubusercontent.com/293280/121730253-4a9a3700-caa4-11eb-9eca-7136965cef50.png)

[Link to Figma](https://www.figma.com/file/jSiXK1x64z3foLqRQfIiIK/Overlay-shadow-validator?node-id=1%3A29)

***

Some thoughts:

- I'm worried about not having enough visual separation for overlays in `dark` mode. If you look at the `light` mode I provided, the shadows render a soft shadow that replaces the need for borders around the overlay. Can we adjust the `dark` version of the shadow to follow a similar pattern? [Example](https://www.figma.com/file/jSiXK1x64z3foLqRQfIiIK/Overlay-shadow-validator?node-id=1%3A19687):
    
    > ![Overlay on dark mode with improved visual separation](https://user-images.githubusercontent.com/293280/121731017-41f63080-caa5-11eb-951f-1ffb4db503e5.png)
- While on `light` mode under a dark canvas (such as the Actions log page), the shadows get a glow instead. That's because the shadow color is a light gray — can that be improved by using a darker tint with adjustments in its alpha?
- Does the `dimmed` mode use the same `dark` mode shadows? They're all looking very dark in my validation files. Can you confirm how this should look like?

Thank you!

2021-06-11 18:52 UTC, vdepizzol requested changes
@simurai I chatted with @auareyou and we covered some quick fixes that would improve the concerns I shared above.

![Figma screenshot](https://user-images.githubusercontent.com/293280/121735022-6a345e00-caaa-11eb-9ad2-085340a7ffc2.png)

[Link to Figma](https://www.figma.com/file/jSiXK1x64z3foLqRQfIiIK/Overlay-shadow-validator?node-id=2%3A166)

2021-06-11 18:52 UTC, vdepizzol commented on data/colors/light.ts
> +    shadow: (theme: any) => `0 1px 3px ${alpha(get('scale.black'), 0.12)(theme)}, 0 8px 24px ${alpha(get('scale.gray.4'), 0.2)(theme)}`,
```suggestion
    shadow: (theme: any) => `0 1px 3px ${alpha(get('scale.black'), 0.12)(theme)}, 0 8px 24px ${alpha(get('scale.gray.7'), 0.12)(theme)}`,
```

2021-06-11 18:52 UTC, vdepizzol commented on data/colors/dark.ts
> +    shadow: (theme: any) => `0 1px 3px ${alpha(get('scale.black'), 0.12)(theme)}, 0 16px 32px ${alpha(get('scale.black'), 0.85)(theme)}`,
```suggestion
    shadow: (theme: any) => `0 0 0 1px ${get('scale.gray.6')(theme), 0 1px 3px ${alpha(get('scale.black'), 0.12)(theme)}, 0 16px 32px ${alpha(get('scale.black'), 0.85)(theme)}`,
```

2021-06-11 18:52 UTC, vdepizzol commented on data/colors_v2/vars/component_dark.ts
> +    shadow: (theme: any) => `0 1px 3px ${alpha(get('scale.black'), 0.12)(theme)}, 0 16px 32px ${alpha(get('scale.black'), 0.85)(theme)}`,
```suggestion
    shadow: (theme: any) => `0 0 0 1px ${get('scale.gray.6')(theme), 0 1px 3px ${alpha(get('scale.black'), 0.12)(theme)}, 0 16px 32px ${alpha(get('scale.black'), 0.85)(theme)}`,
```

2021-06-11 18:52 UTC, vdepizzol commented on data/colors_v2/vars/component_light.ts
> +    shadow: (theme: any) => `0 1px 3px ${alpha(get('scale.black'), 0.12)(theme)}, 0 8px 24px ${alpha(get('scale.gray.4'), 0.2)(theme)}`,
```suggestion
    shadow: (theme: any) => `0 1px 3px ${alpha(get('scale.black'), 0.12)(theme)}, 0 8px 24px ${alpha(get('scale.gray.7'), 0.12)(theme)}`,
```

2021-06-14 03:26 UTC, simurai commented on data/colors/dark.ts
> +    shadow: (theme: any) => `0 0 0 1px ${get('scale.gray.6')(theme), 0 1px 3px ${alpha(get('scale.black'), 0.12)(theme)}, 0 16px 32px ${alpha(get('scale.black'), 0.85)(theme)}`,
Typo

```suggestion
    shadow: (theme: any) => `0 0 0 1px ${get('scale.gray.6')(theme)}, 0 1px 3px ${alpha(get('scale.black'), 0.12)(theme)}, 0 16px 32px ${alpha(get('scale.black'), 0.85)(theme)}`,
```

2021-06-14 03:29 UTC, simurai commented
> @vdepizzol I chatted with @auareyou and we covered some quick fixes that would improve the concerns I shared above.

Ok, great. Committed all the suggestions. 👍

2021-06-14 11:01 UTC, merged